#!/bin/bash

# Executed before a commit is made

echo "Running pre-commit hook"
if [[ `git symbolic-ref HEAD` == "refs/heads/master" ]]
then
	echo "==========================="
	echo "DEAR DEVELOPERS"
	echo "You should not commit in master!"
	echo "Only merges should be made"
	echo "Ask Le Patrick why !"
	echo "If you have a good reason to do it then run git commit with the --no-verify flag"
	echo "(conflicts and stuff like that)"
	echo "Cheers !"
	echo "==========================="
	exit 1
fi
